# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Firebase 
# use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'luvomobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Mapbox
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)

    firebase_static = %w[
      FirebaseCore FirebaseCoreInternal FirebaseInstallations
      GoogleUtilities GoogleAppMeasurement
      FirebaseAnalytics FirebaseCrashlytics FirebaseMessaging 
      FirebaseAuth FirebaseAppCheck FirebaseCoreExtension
      FirebaseAuthInterop RecaptchaInterop FirebaseAppCheckInterop
    ]
      
    installer.pod_targets.each do |pod|
      if firebase_static.include?(pod.name)
        # Force these pods to build as static frameworks
        def pod.build_type
          Pod::BuildType.static_framework
        end
      end
    end
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    # Mapbox
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
