name: CI

on:
  pull_request:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Authenticate private GitHub packages
        env:
          TOKEN: ${{ secrets.LUVO_UI_CI }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${TOKEN}" | base64 -w 0)"
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Authenticate private GitHub packages
        env:
          TOKEN: ${{ secrets.LUVO_UI_CI }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${TOKEN}" | base64 -w 0)"
      - run: yarn install --frozen-lockfile
      - run: yarn typecheck

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Authenticate private GitHub packages
        env:
          TOKEN: ${{ secrets.LUVO_UI_CI }}
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${TOKEN}" | base64 -w 0)"
      - run: yarn install --frozen-lockfile
      - run: yarn test --ci
